global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API monitoring
  - job_name: 'yfinance-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8000']